---

- id: scala-test-run
  name: scalatest
  language: system #since we're running a command directly
  always_run: true
  pass_filenames: false
  verbose: true
  entry: sbt
  args: [ 'partner-api/test;partner-api/it:test;' ]

